config/routes.rb
FriendThings::Application.routes.draw do
  resources :things

  resources :users

end

app/models/thing.rb
class Thing < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :image_url, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :age, :name
  has_many :follower_relations, foreign_key: :user_id, class_name: :UserRelation
  has_many :followed_relations, foreign_key: :friend_id, class_name: :UserRelation
  has_many :followers, through: :follower_relations
  has_many :followeds, through: :followed_relations, source: :followed1
  has_many :things
  def friends 
    (self.followers + self.followeds).uniq
  end

  def friends_friends
    self.friends.collect{|x|x.friends}.flatten.uniq - [self]
  end

  def friends_friends_things
    self.friends_friends.collect{|x|x.things}.flatten.uniq
  end
end

app/models/user_relation.rb
class UserRelation < ActiveRecord::Base
  attr_accessible :friend_id, :user_id
  belongs_to :followed1, class_name: :User, foreign_key: :user_id
  belongs_to :follower, class_name: :User, foreign_key: :friend_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  # GET /things
  # GET /things.json
  def index
    @things = Thing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @things }
    end
  end

  # GET /things/1
  # GET /things/1.json
  def show
    @thing = Thing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/new
  # GET /things/new.json
  def new
    @thing = Thing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/1/edit
  def edit
    @thing = Thing.find(params[:id])
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(params[:thing])

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render json: @thing, status: :created, location: @thing }
      else
        format.html { render action: "new" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /things/1
  # PUT /things/1.json
  def update
    @thing = Thing.find(params[:id])

    respond_to do |format|
      if @thing.update_attributes(params[:thing])
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing = Thing.find(params[:id])
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to things_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FriendThings</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/things/_form.html.haml
= form_for @thing do |f|
  - if @thing.errors.any?
    #error_explanation
      %h2= "#{pluralize(@thing.errors.count, "error")} prohibited this thing from being saved:"
      %ul
        - @thing.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :image_url
    = f.text_field :image_url
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/things/edit.html.haml
%h1 Editing thing

= render 'form'

= link_to 'Show', @thing
\|
= link_to 'Back', things_path

app/views/things/index.html.haml
%h1 Listing things

%table
  %tr
    %th Name
    %th User
    %th Image url
    %th Description
    %th
    %th
    %th

  - @things.each do |thing|
    %tr
      %td= thing.name
      %td= thing.user
      %td= thing.image_url
      %td= thing.description
      %td= link_to 'Show', thing
      %td= link_to 'Edit', edit_thing_path(thing)
      %td= link_to 'Destroy', thing, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Thing', new_thing_path

app/views/things/new.html.haml
%h1 New thing

= render 'form'

= link_to 'Back', things_path

app/views/things/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @thing.name
%p
  %b User:
  = @thing.user
%p
  %b Image url:
  = @thing.image_url
%p
  %b Description:
  = @thing.description

= link_to 'Edit', edit_thing_path(@thing)
\|
= link_to 'Back', things_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :age
    = f.number_field :age
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Age
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.age
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Age:
  = @user.age

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path